from __future__ import annotations

KNOWN_FINDING_CODES = {
    "contract.unknown_dataset",
    "dataset.missing_file",
    "dataset.read_error",
    "discovery.no_products",
    "freshness.missing",
    "freshness.no_values",
    "freshness.stale",
    "freshness.unknown_column",
    "manifest.load_error",
    "policy.access_notes",
    "policy.allowed_purposes",
    "policy.unknown_sensitive_field",
    "quality.accepted_values",
    "quality.expression",
    "quality.invalid_check",
    "quality.max",
    "quality.min",
    "quality.not_null",
    "quality.row_count_min",
    "quality.unique",
    "quality.unknown_column",
    "schema.missing_column",
    "schema.nullable",
    "schema.type_mismatch",
    "semantic.expression",
    "semantic.unknown_column",
    "semantic.unknown_dataset",
    "semantic.unknown_dimension",
    "semantic.unknown_key",
    "suppression.unused",
}
